name: "Update list"

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
      - name: Compile new version
        id: version
        run: |
              npm i -g @adguard/hostlist-compiler
              rm -rf blocklist.txt
              hostlist-compiler -c hostlist-compiler-config.json -o blocklist.txt
              sed -i 's/www\.//g' blocklist.txt
              wc -l blocklist.txt
              head blocklist.txt
      - name: Push new version to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          commit_message: "Update list"